### ISSUE TITLE
No library called "cairo____" was found

### ISSUE THREAD

**Issue by dima059** [ulex/generate_license_plates#2]
Здравствуйте! Не могу запустить Ваш генератор. Ругается на невозможность загрузки библиотек (библиотеку cairosvg установил). Буду благодарен за помощь в решении проблемы!

```
D:\Folder >"C:/Program Files/Python39/python.exe" "d:/Folder/generatenumber.py" a777aa59 
Traceback (most recent call last):
  File "d:\Folder\generatenumber.py", line 36, in <module>
    svg2png(code, pngout)
  File "d:\Folder\generatenumber.py", line 4, in svg2png
    import cairosvg
  File "C:\Program Files\Python39\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Program Files\Python39\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Dmitry\AppData\Roaming\Python\Python39\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Dmitry\AppData\Roaming\Python\Python39\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

**Comment by dima059** [comment]
Оказывается, после установки cairosvg нужно было перезапустить комп 🤦
